### ISSUE TITLE
分隊VCが時に削除されない問題

### ISSUE THREAD

**Issue by merunno** [BattleFieldJapanCommunity/bfbot#28]
- 誰かが利用したあとの分隊VCが残り続けてしまうことがある
- 誰かが分隊VCに参加して抜ければ削除される
- 考えられる線は **Discord APIのレート制限** 。
- もしレート制限であれば直しようがないが別の要因も考えられるので調べて欲しい。

![image](https://user-images.githubusercontent.com/82575685/132996356-a499eea6-16fd-44a0-b1ce-cf84de106e32.png)

**Comment by tksskt** [comment]
事象の再現できないから何とも言えないけど

rate limit の確認した方がいいかも？
`discord.Client().is_ws_ratelimited()`
でtrueが返ってきたらレート制限かかってる説濃厚、あとレート制限時に**on_error**か**on_command_error**吐くらしいからそこも確認した方がいいかも

**Comment by merunno** [comment]
> 事象の再現できないから何とも言えないけど
> 
> rate limit の確認した方がいいかも？
> `discord.Client().is_ws_ratelimited()`
> でtrueが返ってきたらレート制限かかってる説濃厚、あとレート制限時に**on_error**か**on_command_error**吐くらしいからそこも確認した方がいいかも
> @Edqrt @merunno

コンソール見れるのが、Edaくんだけだから見てもらうしか無いかな多分、

**Comment by Edqrt** [comment]
原因は特定済。レートリミットではない。
単にボイスチャンネルのステータスアップデート時の処理の問題だった。
対応します。
